### ISSUE TITLE
Error when running script. Line 13

### ISSUE THREAD

**Issue by sideh** [AmazingWizard/Printer-Dashboard#1]
Hey mate,

Get an error when running this in Poweshell, says there is an error on line 13 as there is no closing bracket after:
 Where-Object {

I brought the line below it  up, not sure if that was the right thing to do or not?

Thanks for making this!

**Comment by AmazingWizard** [comment]
Oh I see the issue. I was using several `where-object` filters on that line and took them out because they were pretty environment specific. I think what you need to do is put a '}' on line 14 after then `"Add Your Filter Here"` line. It pipes a out to another where object to cut down the selection again, but I never closed the first `where-object`

**Comment by AmazingWizard** [comment]
This should be solved now.
